spring.application.name=ms-user

# ===========SERVER===============

server.port=8081

# ===========DATABASE=============

spring.datasource.url=jdbc:postgresql://ep-floral-heart-at7zindi-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JHz4sqPY3VFi

spring.datasource.driver-class-name=org.postgresql.Driver

# ===========JPA==================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========FLYWAY===============

spring.flyway.enabled=true
spring.flyway.baseline-on-migration=true

# ===========API-DOCS=============

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true