spring.application.name=donation

server.port=8083

# DataBase
spring.datasource.url=jdbc:postgresql://ep-fragrant-lake-advjty35-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3OfYicBZCjo9

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true