apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-donation

spec:

  replicas: 1

  selector:
    matchLabels:
      app: ms-donation


  template:

    metadata:
      labels:
        app: ms-donation


    spec:

      containers:

        - name: ms-donation

          image: donaton-proyect-ms-donation:latest
          imagePullPolicy: IfNotPresent
          env:
              - name: DB_URL
                value: "jdbc:postgresql://postgres-donation-service:5432/db_donation"
              - name: DB_USER
                value: "neondb_owner"
              - name: DB_PASSWORD
                value: "password123"
              - name: SPRING_FLYWAY_REPAIR_ON_MIGRATE
                value: "true"

          ports:

            - containerPort: 8083