spring.application.name=MS-Usuarios

server.port=8081

spring.datasource.url=jdbc:postgresql://ep-super-scene-am24yz1z-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GStLM2gcV3qu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false