spring.application.name=APIUsuario



spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083

spring.flyway.enabled=false