apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-campaign


spec:

  replicas: 1


  selector:

    matchLabels:
      app: ms-campaign


  template:

    metadata:

      labels:
        app: ms-campaign


    spec:

      containers:

        - name: ms-campaign

          image: donaton-proyect-ms-campaign:latest
          imagePullPolicy: IfNotPresent
          env:
              - name: DB_URL
                value: "jdbc:postgresql://postgres-campaign-service:5432/db_campaign"
              - name: DB_USER
                value: "neondb_owner"
              - name: DB_PASSWORD
                value: "password123"
              - name: SPRING_FLYWAY_REPAIR_ON_MIGRATE
                value: "true"

          ports:

            - containerPort: 8084