apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-campaign-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-campaign-db
  template:
    metadata:
      labels:
        app: postgres-campaign-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: "db_campaign"
            - name: POSTGRES_USER
              value: "neondb_owner"
            - name: POSTGRES_PASSWORD
              value: "password123"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-campaign-service
spec:
  selector:
    app: postgres-campaign-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432