apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-user

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ms-user

  template:
    metadata:
      labels:
        app: ms-user

    spec:
      containers:
        - name: ms-user
          image: donaton-proyect-ms-user:latest
          imagePullPolicy: IfNotPresent
          env:
              - name: DB_URL
                value: "jdbc:postgresql://postgres-user-service:5432/db_user"
              - name: DB_USER
                value: "neondb_owner"
              - name: DB_PASSWORD
                value: "password123"
              - name: SPRING_FLYWAY_REPAIR_ON_MIGRATE
                value: "true"

          ports:
            - containerPort: 8081