spring.application.name=bff

server.port=8080

# MICROSERVICIOS
auth.service.url=http://localhost:8082
user.service.url=http://localhost:8081
donation.service.url=http://localhost:8083

# ACTUATOR

management.endpoints.web.exposure.include=health,info

# SWAGGER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true